### ISSUE TITLE
.ogg streams are not working

### ISSUE THREAD

**Issue by dilumn** [analogcode/Swift-Radio-Pro#102]
Recently I was working on a sample streaming project & realised that `.ogg` streams are not woking.

Is there a solution for that? or else this project doesn't support `.ogg` streams??

**Comment by analogcode** [comment]
That's a good question. What are some good ogg libraries/frameworks for iOS these days? Anyone know?

**Comment by fethica** [comment]
After a quick research, I found this one: https://github.com/brion/OGVKit you could just import the Vorbis audio framework.

**Comment by dilumn** [comment]
Thanks for your quick reply. I installed `OGVKit` into the project. But how can I use OGVPlayer for the radio play?

**Comment by dilumn** [comment]
Thanks for your help @fethica && @analogcode
