### ISSUE TITLE
iOS 12 Compatibility 

### ISSUE THREAD

**Issue by mannyd209** [analogcode/Swift-Radio-Pro#104]
Is iOS 12 compatibility in the cards and/or CarPlay, Siri shortcuts?

**Comment by fethica** [comment]
The dev branch is already updated to Xcode 10 and Swift 4.2 (iOS 9 is no longer supported) you can check it out, if you implement anything related to CarPlay or Siri shortcuts feel free to open a PR if that keeps the app simple to customize and without dependencies. Thanks.

**Comment by mannyd209** [comment]
Thanks @fethica

**Comment by urayoanm** [comment]
> 
> 
> Is iOS 12 compatibility in the cards and/or **CarPlay**, Siri shortcuts?

@mannyd209 , recently i did implement Carplay in my app, and the steps was farly easy. First, you need to ask Apple to give you the entitlement. Use this form to request it.

https://developer.apple.com//contact/carplay/

In the tell us about your product, use something similar like this:

**We are a radio station with listeners who commute and we put a lot of focus on our mobile apps.  Can you please approve?**

It takes a few days to receive the approval. After that, Apple send you the document of what you need to do to implement and use the entitlement.

In my case, i implement the NowPlay screen and the options to Play, Pause, and vote for songs. The min iOS version that i am using is iOS 11, but i think the iOS 10 can work as well.

**Comment by mannyd209** [comment]
Thanks so much @urayoanm So I’ve got the entitlement already from Apple just trying to figure out where I input code to get it to send to CarPlay. If you can help me out, it would be much appreciated. Thank you sir.

**Comment by urayoanm** [comment]
> 
> 
> Thanks so much @urayoanm So I’ve got the entitlement already from Apple just trying to figure out where I input code to get it to send to CarPlay. If you can help me out, it would be much appreciated. Thank you sir.

@mannyd209, right now are you using the app for live streming?

**Comment by mannyd209** [comment]
@urayoanm Yessir, I run 4 stations through it. I’m a beginner developer but learning quickly. It is on the App Store for free.

**Comment by urayoanm** [comment]
> 
> 
> @urayoanm Yessir, I run 4 stations through it. I’m a beginner developer but learning quickly. It is on the App Store for free.

Another quick question, and you have a default station that play music when the app open? 

In my case, i did not yet use the tabbed option for the Carplay to select another station and show more options (work in progress AKA figuring out that part :-)).

**Comment by urayoanm** [comment]
> 
> 
> @urayoanm No it doesn’t auto play, you have to select one of the stations to play. If you steer me in the right direction, I could probably make it work. Thanks again sir.

Hello @mannyd209 . Let me try to modify the master example with Carplay Support and i let you know when i have it with all the pieces. 
Right now (quick modifications), and i am able to see the now playing screen in the external Carplay monitor (using the simulator). As soon as i figure it out how to list he stations and get actions i will post here to let you know.

**Comment by mannyd209** [comment]
@urayoanm Thanks so much sir.

**Comment by iDevelopper** [comment]
Hi @urayoanm , what about your tests about CarPlay?

**Comment by fethica** [comment]
Hi guys, I created a new branch for CarPlay: https://github.com/analogcode/Swift-Radio-Pro/issues/110

**Comment by Sj7800** [comment]
Hi Fethica,

I am making one Navigation app for carplay. I followed the procedure shown by your app to my navigation app doing some changes using Apple Documentation.

I am facing a problem that the maps are not displaying on my simulator screen. Only the starting page is shown.

Can you please help me how to do it?

Thanks
Sj

**Comment by losgranos** [comment]
From my experience it doesnt show up on the simulator you need to install it on your phone then test it on the car... unless i'm doing something wrong...

**Comment by Sj7800** [comment]
Oki let me check

Sent from my iPhone

On 30-Jan-2020, at 22:11, losgranos <notifications@github.com<mailto:notifications@github.com>> wrote:


From my experience it doesnt show up on the simulator you need to install it on your phone then test it on the car... unless i'm doing something wrong...
