### ISSUE TITLE
Minor issue

### ISSUE THREAD

**Issue by losgranos** [analogcode/Swift-Radio-Pro#105]
I'm getting a couple of these "Using '!' here is deprecated and will be removed in a future release" any way i can rid of these?

thanks in advance
juan

**Comment by fethica** [comment]
Hey @losgranos, did you check if the issue is present on the dev branch? Thanks.

**Comment by losgranos** [comment]
@fethica i started with fresh file, just downloaded it from the master... should I be using a diffrent one?

**Comment by fethica** [comment]
@losgranos Yes try the dev branch instead, it's the most recent code, not merged to master yet since iOS 9 will no longer be supported.

**Comment by losgranos** [comment]
Ah ok, of course that makes sense... totally forgot! thanks!
