### ISSUE TITLE
Now Playing Album Artwork

### ISSUE THREAD

**Issue by mannyd209** [analogcode/Swift-Radio-Pro#111]
Hey guys I'm trying to get the Now Playing album artwork to pull from our station RDS. I was able to implement it in a "Recently Played" view controller that I added. See the video that I attached.
[ScreenRecording](https://imgur.com/bvGLDYv)

So is there a way to have the now playing pull the artwork URL from our station RDS?
If not then is there a way to have the now playing pull an image from a URL if a certain Artist or Album is currently playing? The reason for this is we have guest DJs that mix for an hour each day and we would like to show their image while they are in the mix. 

Thanks guys

**Comment by urayoanm** [comment]
Hi. I did something similar with my app, but i use the album name to send specific tag. Before the call for the iTunes API y search for that part. If exist y look for specific art hosted in our servers. As today, ot works like a charm. In my case, the tag is AZComm, for example AZCommHandlebar. If in album art, AZComm exists I compose the url based on that (ill give you and example later when i am in the computer).

**Comment by mannyd209** [comment]
Sweet @urayoanm thanks and yes I would love to see how you made it work for you. Thanks Again!

**Comment by urayoanm** [comment]
@mannyd209 this is a quick modification of the class in FRadioPlayer to accomplish what I am telling earlier.

To test with my tags use this streaming
http://cassini.shoutca.st:9300

Then replace the FRadioAPI.swift with my example. Dirty one, but it shows the concept of what im telling you. Remember to make backup of the original class. I did change the extension to txt because Github does not permit .swift files in this comments.

Hope this helps

The metadata format of my streaming is defined as Song - Artist - Album

[FRadioAPI.txt](https://github.com/analogcode/Swift-Radio-Pro/files/2891836/FRadioAPI.txt)

**Comment by urayoanm** [comment]
An example of what I am explaining with a clean source of Swift Radio Pro. The displayed art as 8:24PM is custom

:)
![simulator screen shot - iphone xr - 2019-02-21 at 20 23 29](https://user-images.githubusercontent.com/15786066/53211171-b5df4700-3616-11e9-9cca-b881e0f3abda.png)

**Comment by urayoanm** [comment]
BTW, i know is not the most elegant edit to that precious class, but i think is part of the learning curve 😅

**Comment by mannyd209** [comment]
Thanks soooo much. I'm going to give it a try tomorrow morning when I'm back in the office. I will let you know how it goes. Also would I be able to use this method of yours for multiple artworks for multiple shows? Thanks again!!!

**Comment by urayoanm** [comment]
No problem. And yes, you can use that in anything you want. In songs, bumpers, stingers etc. 

Usually, when a dj is live and is going to speak, put that in the intro, or update the metadata manually. We use it even in commercials.

**Comment by urayoanm** [comment]
Just an observation in your stream with the app, in our case, even the commercials and bumpers send metadata. Sometimes is a tweak in the automatation software.

**Comment by mannyd209** [comment]
@urayoanm So what metadata is it looking for? The Artist, Track Title, Album or something else? I tried using your code example and it's not working for me. Maybe I'm doing something wrong.

**Comment by urayoanm** [comment]
@mannyd209 , the part it is looking for is at the Album part of the metadata. For example, an usual metadata string I receive from my server is like this
KISS - 2,000 Man - Live - MTV Unplugged

**Artist - Song Name - Album**

And example for Station ID in our station:
AZ Rock - We Know Music from A to Z - **AZCommStationID** 

When I split the string I look for the third part of the string, in my case the album name in the mp3 / wav file.

Our songs not always have the Album part, but the commercials, bumpers and all the station stuff is mandatory.

In the album part I put the tag I defined to complete the custom art I want to look for. Usually it is posted in our web site.

Make sure the automation software sends the album part if it is available in your music / station recordings and the metadata for the commercials and bumpers is send as well.

**Comment by mannyd209** [comment]
@urayoanm I'm having some issues. I think I'm not doing it correctly. Can you message me on Twitter or Reddit? I have a few questions for you if you don't mind? My username is: DJMannyD
