### ISSUE TITLE
NSErrorFailingURLStringKey

### ISSUE THREAD

**Issue by brdn** [analogcode/Swift-Radio-Pro#112]
Hi, any idea ? url is working but player cant play it
NSErrorFailingURLStringKey=http://nashe1.hostingradio.ru/best-128.mp3

load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled

**Comment by urayoanm** [comment]
I think this can help you out
https://stackoverflow.com/questions/33146003/afnetworking-with-request-error-code-999

**Comment by brdn** [comment]
i'm already using this solution, still have the same issue.

**Comment by fethica** [comment]
Hey @brdn, the link you provided is protected with a user and password, I'm getting this when I try to play the stream using Safari:

<img width="474" alt="screen shot 2019-03-05 at 3 34 56 pm" src="https://user-images.githubusercontent.com/3511384/53835854-6ecd4c00-3f5c-11e9-9a29-40a4c8e256e3.png">

If you have the credentials for the stream, try to use this URL format instead:
```
http://username:password@nashe1.hostingradio.ru/best-128.mp3
```

**Comment by brdn** [comment]
> Hey @brdn, the link you provided is protected with a user and password, I'm getting this when I try to play the stream using Safari:
> 
> <img alt="screen shot 2019-03-05 at 3 34 56 pm" width="474" src="https://user-images.githubusercontent.com/3511384/53835854-6ecd4c00-3f5c-11e9-9a29-40a4c8e256e3.png">
> 
> If you have the credentials for the stream, try to use this URL format instead:
> 
> ```
> http://username:password@nashe1.hostingradio.ru/best-128.mp3
> ```

thats weird,
i try on mozilla & chrome and i dont get any problem, only on safari its asking username and password.

**Comment by fethica** [comment]
I checked the response header, and I found the media link is pointing to:
```
http://nashe1.hostingradio.ru/best-256
```
It's working with Safari and the app.

**Comment by brdn** [comment]
256k= more bandwith, but its a **solution** :) 
Thank you
