### ISSUE TITLE
currentTime

### ISSUE THREAD

**Issue by KheangSenghort** [analogcode/Swift-Radio-Pro#113]
Dear Sir/Madam

I want to get current time when loading url from server. 
Why your class not provide this method to access so that?
What should I do, If I want to get total time of song?
I'll waiting feedback result from you as soon as.

Thanks

**Comment by fethica** [comment]
Hi @KheangSenghort 

Currently, we don't support the `currentTime` in the project, the live stream audio doesn't need this feature.
