### ISSUE TITLE
App Rejected

### ISSUE THREAD

**Issue by paulgnz** [analogcode/Swift-Radio-Pro#120]
> Guideline 2.1 - Performance - App Completeness
> 
> 
> We discovered one or more bugs in your app when reviewed on iPad running iOS 12.2 on Wi-Fi.
> 
> Specifically, no sound is produced when the app is launchd. The app remains frozen on the initially launched screen. 
> 
> Next Steps
> 
> To resolve this issue, please run your app on a device to identify any issues, then revise and resubmit your app for review.
> 
> If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.
> 
> For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce the issue. For updates, install the new version as an update to the previous version, then follow the steps to reproduce the issue.
> 
> Resources
> 
> For information about testing your app and preparing it for review, please see Technical Note TN2431: App Testing Guide. 
> 
> For a networking overview, please review About Networking.
>

**Comment by analogcode** [comment]
Does your app work when you test it under that scenario? (on a device - iPad running iOS 12.2 on Wi-Fi) 
If it does, maybe try re-submitting?

**Comment by paulgnz** [comment]
I fixed this by clicking "requires full screen" in xcode and then resubmitting. Approved within 24 hours. Thank you!

**Comment by iDevelopper** [comment]
What is the relation?

**Comment by analogcode** [comment]
Glad you got it figured out, @paulgnz!
