### ISSUE TITLE
Website link

### ISSUE THREAD

**Issue by joshopkins787** [analogcode/Swift-Radio-Pro#125]
I have entered our in PopUpMenuViewController.swift by updating it where says //User you own website URL here. But whenever it is clicked on it goes to https://url.org/dms and wants to save the dms file to the device instead of opening the site.

**Comment by fethica** [comment]
I have just tested the code, and it's working fine with new urls:

```swift
/// PopUpMenuViewController

@IBAction func websiteButtonPressed(_ sender: UIButton) {
        // Use your own website URL here
        guard let url = URL(string: "https://fethica.com") else { return }
        UIApplication.shared.open(url, options: [:], completionHandler: nil)
}
```

Maybe there is a header redirection issue in your website.
