### ISSUE TITLE
unable to connect to "(null)" when launching CarPlay in simulator 

### ISSUE THREAD

**Issue by DavidDHansson** [analogcode/Swift-Radio-Pro#133]
Hi, I have cloned the entire CarPlay repository. When launching the simulator and the CarPlay, I'm greeted with a blank screen. There is an empty navigation bar at the top, with 3 empty options. When "pulling up" to refresh, the text "unable to connect to "(null)"" is shown. 

Thanks in advance.

**Comment by tester89** [comment]
Same issue here. Can't find anywhere to fix this.

**Comment by fethica** [comment]
Hi, this is an issue with the iOS 13 simulator and still not fixed yet, the only way to test your CarPlay apps is to install an iOS 12 simulator or using a real CarPlay head unit in your car.
