### ISSUE TITLE
IOS 13 Background audio play stopped

### ISSUE THREAD

**Issue by jose2016** [analogcode/Swift-Radio-Pro#134]
Hello first of all many thanks for put this beautiful app open source all work fine but why the app is not playing the audio in background, before was working, when the app change to another app, the music stopped until is opened again. That is cool like youtube but not comfortable.
Any suggestion.

**Comment by fethica** [comment]
Hi @jose2016, I've just tested the app and it's working fine in the background, make sure that the background mode is checked for `Audio, Airplay and PiP` in the capabilities section:

![Screen Shot 2019-12-28 at 8 55 12 PM](https://user-images.githubusercontent.com/3511384/71551396-7448c680-29b4-11ea-8479-32fb78dff9c8.png)

**Comment by jose2016** [comment]
Hey there thanks for your quickly answer and Happy new year 🎊 
The issue is solved @fethica
