### ISSUE TITLE
ITMS-90683: Missing Purpose String in Info.plist  error....

### ISSUE THREAD

**Issue by losgranos** [analogcode/Swift-Radio-Pro#138]
Any idea how to fix this? Haven't been able to figure it out... thanks...

Dear Developer,

We identified one or more issues with a recent delivery for your app.. Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more

**Comment by fethica** [comment]
The app doesn't use any user location data, are you using any other frameworks (like analytics, ads ...) that uses user location? If that's the case, you need to add `Privacy - Location Always Usage Description` to your info.plist file with a description to why you want to access this information.

**Comment by losgranos** [comment]
All I added was my radio stream link I haven't changed anything else in the code...

**Comment by fethica** [comment]
@losgranos Any updates on this? We've published several apps to the App Store and this issue never come app.

**Comment by losgranos** [comment]
@fethica the apps are published with no issues, I assume it’s just a warning for something they going to implement in the future?

**Comment by fethica** [comment]
@losgranos yeah maybe, we'll keep an eye on it if they change something in the future, we will align to the new guidelines. Thanks for raising the issue!
