### ISSUE TITLE
Metadata not working

### ISSUE THREAD

**Issue by timbruenjes** [analogcode/Swift-Radio-Pro#150]
If there is a semikolon in the Artist/Title Information the Metadata doesn‘t update

**Comment by fethica** [comment]
With the new update you can implement your own [`FRadioMetadataExtractor`](https://github.com/fethica/FRadioPlayer/blob/v0.2.0/Sources/FRadioPlayer/FRadioMetadataExtractor.swift#L10) and extract metadata from `[AVTimedMetadataGroup]`
