### ISSUE TITLE
Now Playing view broken in landscape

### ISSUE THREAD

**Issue by PocketTim** [analogcode/Swift-Radio-Pro#151]
The whole interface works fantastically in landscape except the now playing view. Any chance we could get this fixed? I've tried myself but not had much luck.

Thank you.

**Comment by iDevelopper** [comment]
It is not broken. The application was never designed to work in landscape mode!

**Comment by PocketTim** [comment]
> 
> 
> It is not broken. The application was never designed to work in landscape mode!

My apologies, didn't mean to cause offence. Just noticed coincidentally that all of the UI works so well in Landscape other than that one screen that it might have been a bug that it doesn't. Clearly not. I've modified the app so much that I'd forgotten what the defaults were tbh!

Anyway sorry again, it's a fantastic app and I really appreciate the work that has gone into it.
