### ISSUE TITLE
CarPlay branch needs fix

### ISSUE THREAD

**Issue by losgranos** [analogcode/Swift-Radio-Pro#158]
Any idea how to fix this, I tried searching google no real answers, just more questions lol

'MPPlayableContentDelegate' was deprecated in iOS 14.0: Use CarPlay framework

thanks!

**Comment by fethica** [comment]
It's deprecated but as of iOS 16 it's still working, we are planning to migrate to the new CarPlay but we'll probably have to drop support for older iOS versions.

**Comment by iDevelopper** [comment]
You do not have to drop support for older versions. You can have the two entitlements from Apple (com.apple.developer.playable-content and com.apple.developer.carplay-audio for iOS 14 +). And use them for the same App.
