### ISSUE TITLE
Is CarPlay in the cards?

### ISSUE THREAD

**Issue by bricedupuy** [analogcode/Swift-Radio-Pro#22]
Just found out about this project,
I'm excited to give it a try.

Anyone with the knowledge to implement this?
How about Google Chromecast?

**Comment by Jxrgxn** [comment]
No knowledge on how to implement it but I'm definitely interested. I labeled it as a enhancement.

**Comment by orassr** [comment]
found issues with bluetooth connection, was wondering if  using this library would help ?
https://github.com/troystribling/BlueCap

**Comment by donlent** [comment]
Hello everybody!
Have a look at this official Apple websites. There are two videos that show how to implement CarPlay.
https://developer.apple.com/carplay/
Anyone with the knowledge of doing a first-run implementation of this feature?

Would be GREAT!!!

Thanks!!

**Comment by swiftcodex** [comment]
Update: Apple has still not opened the CarPlay API up for use in Open-Source projects. When it does, I would definitely be interested in adding this.

**Comment by ChochoD** [comment]
I abandoned my project. Everything was ready but after I realized it is not streaming the audio to my BT radio I gave up. I won't touch anything unless this is fixed.

**Comment by swiftcodex** [comment]
@ChochoD Could you elaborate? Bluetooth works fine. CarPlay requires a special API and application you have to fill out with apple.

**Comment by swiftcodex** [comment]
Hi @ChochoD, looking at your repo, it looks like you maybe using code from March. Are you setting your AVAudioSessionCategory to playback (instead of playback and record). It should look similar to this: https://github.com/swiftcodex/Swift-Radio-Pro/commit/82252c45f5c052d982d57166062e551a89a83b0f

**Comment by RBrenet** [comment]
I have contact apple for this feature.

To enable carplay emulator, you just put this in terminal : 
defaults write com.apple.iphonesimulator CarPlay -bool YES

In simulator > Hardware > External Display > CarPlay

**Comment by swiftcodex** [comment]
@RomainDev25 That's excellent information, thank you

**Comment by wwninteractive** [comment]
Hello all, I wanted to share my 2 cents on this.  The bluetooth connection is working perfectly.  However, it is important to note that if you are using Swift Radio in single station configuration, you need to make sure AVAudioSessionCategoryOptions.allowBluetooth is included in the Nowplaying controller.  I converted the multi station to a single and realized that the stations view controller is not used, therefore the allowBluetooth is never passed.  Once I put it on the Nowplaying controller everything works as expected.  Cheers!!

**Comment by kryptics** [comment]
Ah nice- I just been using the multi-station one and deleting the other stations, any chance you could upload your code??

**Comment by wwninteractive** [comment]
one more thing, if you notice the quality of your audio on blue tooth is poor change    AVAudioSessionCategoryPlayAndRecord, to  AVAudioSessionCategoryPlayback

**Comment by fethica** [comment]
CarPlay branch added to the project: https://github.com/analogcode/Swift-Radio-Pro/issues/110
