### ISSUE TITLE
Code Update NowPlayingViewController.swift

### ISSUE THREAD

**Issue by jmtaverne** [analogcode/Swift-Radio-Pro#59]
Hi, 

You can add following code in the NowPlayingViewController.swift file for automatically changing the Volume Slider by pressing the Volume-keys on your device. It doesn't worked for me before. This code is working in Swift 3.

Add in ViewDidLoad:

`listenVolumeButton()`

Add following functions:

 ```
func listenVolumeButton(){
        let audioSession = AVAudioSession.sharedInstance()
        do{
            try audioSession.setActive(true)
            let vol = audioSession.outputVolume
            print(vol.description) //gets initial volume
        }
        catch{
            print("Error info: \(error)")
        } 
        audioSession.addObserver(self, forKeyPath: "outputVolume", options:
            NSKeyValueObservingOptions.new, context: nil)    
    }
    
    override func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?) {
        if keyPath == "outputVolume"{
            let volume = (change?[NSKeyValueChangeKey.newKey] as!
                NSNumber).floatValue
            print("volume " + volume.description)
            slider?.value = volume
        }
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        let audioSession = AVAudioSession.sharedInstance()
        audioSession.removeObserver(self, forKeyPath: "outputVolume")    
    }
```

**Comment by swiftcodex** [comment]
@jmtaverne - Do you want to make a PR so you get credit for it in github?

**Comment by jmtaverne** [comment]
@swiftcodex - Thank you for that tip. I created a Pull Request.

**Comment by JazzBallet** [comment]
@jmtaverne Hi. I've been able to use this principle before, but since the last update of iOS it doesn't seem to work any longer. Maybe you have a better understanding of it than me to know why this might have happened, and if there's a workaround for it? I'm running iOS 11.2. Thanks.

**Comment by fethica** [comment]
@jmtaverne @JazzBallet , this issue has been fixed in the version 2 of the app available now on master. Thanks!
