### ISSUE TITLE
Crash when "search" enabled

### ISSUE THREAD

**Issue by stellz** [analogcode/Swift-Radio-Pro#80]
1.Set searchable to "true"
2.Build and run
3.Pull down to show the search bar
4.Try to enter keyword in the search bar
5.Crash 
[<SwiftRadio.RadioStation 0x1c00fe500> valueForUndefinedKey:]: this class is not key value coding-compliant for the key stationName.

**Comment by akuzminskyi** [comment]
@stellz As I see the issue fixed in **dev** branch, so you can checkout source code from this branch.

**Comment by fethica** [comment]
@akuzminskyi Thanks for confirming that!

**Comment by stellz** [comment]
Yes, you are right, I forgot to check the dev branch. Should I close the issue or should it stay open until the fix is merged into the master branch? Happy holidays everyone!

**Comment by fethica** [comment]
@stellz Yes I think it's best to leave it open until the dev branch gets merged. Thanks!

**Comment by fethica** [comment]
The dev branch has been merged!
