### ISSUE TITLE
I need Custom user agent

### ISSUE THREAD

**Issue by naguchennai** [analogcode/Swift-Radio-Pro#83]
SIr I need Custom user agent how can i set it? pls help me

**Comment by fethica** [comment]
@naguchennai I don't know if you could pass a custom header directly to `AVURLAsset` using `AVURLAssetHTTPHeaderFieldsKey` I think it's a private API and your app may be rejected! There is some workaround by using a reverse proxy on the device: 

http://kevinjameshunt.com/other-projects/sending-and-receiving-avplayer-http-headers/ 

Hope this helps!
