### ISSUE TITLE
Switching from WiFi to 3G/4G/LTE and vice versa gets the station playing stuck in stop mode.

### ISSUE THREAD

**Issue by mannyd209** [analogcode/Swift-Radio-Pro#84]
I've noticed when you are listening to a station and you move from WiFi to 3G/4G/LTE or vice versa that the station will stop and the only way to get it to come back is to press the STOP button and then play again. Is there anyway we can have the station thats playing to auto restart once DATA is re-established? Other than that I love it, great work guys.

**Comment by mannyd209** [comment]
Awesome, thank you @fethica looking forward to it. You do amazing work. Thank you so much for that.

**Comment by fethica** [comment]
@mannyd209 I think the bug for network switching is related only to iOS 11 according to this radar issue: https://openradar.appspot.com/radar?id=4989228005982208 The player should be reset after a network interruption

**Comment by mannyd209** [comment]
@fethica Yup I just tested that and you are correct. So we just wait for Apple to fix this issue or do we work around it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fethica** [comment]
@mannyd209 Thanks for confirming that, I'm planning to add network interruption handling to FRadioPlayer and see if this will fix the issue.

**Comment by mannyd209** [comment]
@fethica Awesome, thank you and you are welcome sir. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fethica** [comment]
@mannyd209 I updated FRadioPlayer to handle network interruptions and the iOS 11 issue, I added it to the project! Could you check if everything is working on your side? Thanks

**Comment by mannyd209** [comment]
@fethica I'm on it now. I'll report back in a few. Thanks!!!!!

**Comment by mannyd209** [comment]
@fethica Works perfect!!!! Thank You so much good sir. On a different note, is there anyway I can load a longer cache of the station thats playing?

**Comment by fethica** [comment]
@mannyd209 You're welcome :)

For your question check the `AVPlayerItem` property [`preferredForwardBufferDuration`](https://developer.apple.com/documentation/avfoundation/avplayeritem/1643630-preferredforwardbufferduration) 

Hope this helps!

**Comment by mannyd209** [comment]
@fethica Thanks for pointing me in the right direction. I'm very new to code but I ran several tests and just can't figure where the best place to input this:
`var preferredForwardBufferDuration: TimeInterval { get set }`
in FRadioPlayer.swift.
I'm not sure if I just need that line with my duration value of seconds in {get set} or if there is more to it? No rush but whenever you have time I would like to learn more on that and maybe implement it in my code eventually. Thanks again for all you do, You Rock!!!!

**Comment by fethica** [comment]
Hey @mannyd209 

`preferredForwardBufferDuration` is an `AVPlayerItem` property, you can access it only in FRadioPlayer since it's a private instance. In your case you can add this to:

```swift
// Line 208 (FRadioPlayer 0.1.9)
private var playerItem: AVPlayerItem? {
        didSet {
            playerItemDidChange()
            if #available(iOS 10.0, *) {
                playerItem?.preferredForwardBufferDuration = 60
            }
        }
}
```
Note that this property is available since iOS 10, also if you edit the FRadioPlayer.swift you will have to do it each time the  library gets updated!

More info: https://developer.apple.com/documentation/avfoundation/avplayeritem/1643630-preferredforwardbufferduration

**Comment by mannyd209** [comment]
@fethica Awesome, thank you again sir. So I went ahead and gave that a try, also ran a few tests and still could not get it to cache more than the 15 seconds that it always has. Maybe I'm doing something wrong.

**Comment by fethica** [comment]
@mannyd209 I don't know exactly how this property works under the hood, but maybe you are getting the 15 seconds because it's a radio stream and you hit the live section by 15 sec. If it was an audio file you could preload the seconds you want since the data is already there!

**Comment by kryptics** [comment]
@mannyd209 the delay is between 15-20 secs thats normal - it has to do with your radio server not the app...

**Comment by mannyd209** [comment]
@fethica & @kryptics thanks guys. I’ll live with the 15sec cache. You can close this issue. Thanks for all the great help.
