### ISSUE TITLE
App crashes on launch only on iOS 9 or 10 but not 11.

### ISSUE THREAD

**Issue by mannyd209** [analogcode/Swift-Radio-Pro#85]
Hey guys I am getting this when I run the app on iOS 9 and 10 but it works perfectly on iOS 11. I see my LaunchScreen but that is it and it stays on the LaunchScreen. Is anyone else having this issue or am I just an idiot? I'm very new to coding and still learning. Thanks

![screen shot 2018-02-21 at 3 56 30 pm](https://user-images.githubusercontent.com/35792166/36512572-e6ff3834-171f-11e8-90e3-fe6d6b451dbc.png)
![screen shot 2018-02-21 at 3 56 52 pm](https://user-images.githubusercontent.com/35792166/36512576-e96ef9a6-171f-11e8-8225-71b6f27a8ee4.png)

**Comment by fethica** [comment]
Hi @mannyd209, thanks for the feedback!

I tested the app on 10.3.3 (iPhone 7+) and 9.3.5 (iPad 2) and everything is working fine, could you share more infos about the iOS version and the devices you used so we can do more testing? Thanks

**Comment by mannyd209** [comment]
I think I might of just figured it out. I had a YouTube Player pod installed in the project that I wasn’t using anymore but hadn’t uninstalled it yet. After I uninstalled it and updated my onesignal notifications pod it now is working on my iOS 9.3 simulator. I’ll try it on an actual physical device once I get to work in an hour from now. I’ll report back then. Thanks for your quick response @fethica 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mannyd209** [comment]
Yup that was the issue. Something to do with the unused YouTube Player Pod. I will now close this issue. Thanks again @fethica 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
