### ISSUE TITLE
Slight fix for the Share button

### ISSUE THREAD

**Issue by ShanghaiTimes** [analogcode/Swift-Radio-Pro#89]
The Share button wasn't working - crashed on the iPad. A little fix for that here. Others may wish to modify if needed.
`    @IBAction func shareButtonPressed(_ sender: UIButton) {
        let songToShare = "I'm listening to \(currentTrack.title) on \(currentStation.name) via Swift Radio Pro"
        let activityViewController = UIActivityViewController(activityItems: [songToShare, currentTrack.artworkImage!], applicationActivities: nil)
        activityViewController.popoverPresentationController?.sourceView = self.view // so that iPads won't crash

        // exclude some activity types from the list (optional)
        //activityViewController.excludedActivityTypes = [ UIActivityType.airDrop, UIActivityType.postToFacebook ]
        
        // present the view controller
        self.present(activityViewController, animated: true, completion: nil)

      /*
        activityViewController.completionWithItemsHandler = {(activityType: UIActivityType?, completed:Bool, returnedItems:[Any]?, error: Error?) in
            if completed {
                // do something on completion if you want
            }
        }
        present(activityViewController, animated: true, completion: nil)
         */
    }`

**Comment by fethica** [comment]
@ShanghaiTimes Thanks,

The app UI for now supports only the iPhone, I will fix the part that causing the crash in case someone wants to use the same UI for the iPad.

**Comment by michaeldelannay** [comment]
hi @fethica what do you think about trying to work on this together now ?
I can add you as a beta tester if you want to know more about the project and hear some cool music.
PLEASE ! 
Kind regards.

**Comment by fethica** [comment]
The iPad support has been added in version 2.0.3: https://github.com/analogcode/Swift-Radio-Pro/releases/tag/2.0.3
