### ISSUE TITLE
Show the song playing for each station in stations list

### ISSUE THREAD

**Issue by alisanalacam** [analogcode/Swift-Radio-Pro#90]
Hi,

i want to show the song playing for each station in stations list
how can do it? or is this feature be on the to do list?

thanks.

**Comment by mannyd209** [comment]
This would be awesome if possible.

**Comment by analogcode** [comment]
If the stations have a playlist feed (aka a recently played feed - https://github.com/analogcode/Swift-Radio-Pro/issues/91), you could monitor all those. However, that's a lot of calls. You will need to make an API call to each station on your list at a predetermined time interval. A better way might be to build a web service that gathers that info, and just make one call to that web service.
