### ISSUE TITLE
Recently played

### ISSUE THREAD

**Issue by mannyd209** [analogcode/Swift-Radio-Pro#91]
Is there a way to possibly get the recently played tracks of a station? I did some digging and found this. Don’t know if this would do it. https://stackoverflow.com/questions/36267549/last-heard-songs-swift

**Comment by analogcode** [comment]
To my knowledge, you would need to get this information from the station. Some radio stations keep a feed of their recently played songs. The other alternative would be to live monitor the radio station to generate a list. Which would take a lot of bandwidth.

**Comment by mannyd209** [comment]
@analogcode Myself along with my Program Director both run the stations ourselves so I guess the info would come from us. I am talking with our streaming service company now to see if they have a database that stores our recently played songs so that I can pull from that. I'll report back soon.

**Comment by mannyd209** [comment]
@analogcode I added the JSON link to each stations Long Description in the local JSON data file. Now if I can just pull that into the now playing view controller and attach it to a button. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
