### ISSUE TITLE
Buy Song

### ISSUE THREAD

**Issue by mannyd209** [analogcode/Swift-Radio-Pro#92]
I also wanted to know if we can implement the option to buy a song that is now playing or in a recently played list? I would like to do it but need a little guidance. Thanks

**Comment by analogcode** [comment]
This is a big question. Do you want to work out licenses with publishers and artists to sell independent music. Or, are you going to work with iTunes and the Apple Music API. If you simply want to allow users to buy the songs on iTunes, that is very simple. However, as the app developer, you will not see any profit from that.

**Comment by mannyd209** [comment]
Awesome thanks @analogcode that is exactly what I needed. Yes I would just like the option to buy on iTunes. I would start digging into this now. Thanks again sir.
