### ISSUE TITLE
UIAlertView deprecated in iOS 9

### ISSUE THREAD

**Issue by kryptics** [analogcode/Swift-Radio-Pro#95]
I guess with the new XCode new depreciations... any ideas how to fixed this one?

'UIAlertView' was deprecated in iOS 9.0: UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead

@fethica @analogcode 

again, thanks in advance!

**Comment by fethica** [comment]
Hey @kryptics 

Are you using the new version of the app? It's already using the `UIAlertController`:

```swift
// AboutViewController

func showSendMailErrorAlert() {
    let sendMailErrorAlert = UIAlertController(title: "Could Not Send Email", message: "Your device could not send e-mail.  Please check e-mail configuration and try again.", preferredStyle: .alert)
    let cancelAction = UIAlertAction(title: "OK", style: .cancel, handler: nil)

    sendMailErrorAlert.addAction(cancelAction)
    present(sendMailErrorAlert, animated: true, completion: nil)
}
```

**Comment by analogcode** [comment]
I'm closing this issue. Reason: The project has been updated.
