### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [analogcode/Swift-Radio-Pro#97]
Hi. I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project and it's free.

**Comment by analogcode** [comment]
Sounds good to me. I can't guarantee we'll use it. But, we'll at least give it proper consideration. Thank you! 🙏

**Comment by mirzazulfan** [comment]
Hi sir @analogcode Sorry for late reply, I've designed a logo for you, if you like it, you can use it. i'll send you files. Tell me if you need some change or anything.
![radio](https://user-images.githubusercontent.com/36124339/41195020-dd1041da-6c4f-11e8-8c65-cbb5633d3978.png)
If you dont like it you can close this issues. Thank you
