### ISSUE TITLE
Using cover art in app

### ISSUE THREAD

**Issue by thejshot** [analogcode/Swift-Radio-Pro#99]
Is it legally permissible to use a song's cover art in the app?

**Comment by analogcode** [comment]
That's a good question. If you actually download and package the artwork in your app bundle, it may be a legal gray area. If you're using Apple's or LastFM's artwork API to stream the art, then it is permissible.

**Comment by thejshot** [comment]
Thanks!

**Comment by iDevelopper** [comment]
In both cases you can't present it as metadata to describe your app on the AppStore. Apple will reject the app.

**Comment by analogcode** [comment]
Thanks @iDevelopper!
